### PR TITLE
Also load config from /etc/elasticsearch/analysis-ik

### PR DESCRIPTION
**Pull request by RobberPhex**
[config files stay with plugin](https://github.com/medcl/elasticsearch-analysis-ik/commit/f9977456ee0135f9b9682e7a8e818da364b08cfa#diff-3e822f7015252733c7e5372514d9623cR38) is not friendly for upgrade elasticsearch or this plugin.

In [official example](https://github.com/elastic/elasticsearch/blob/2.3/plugins/jvm-example/src/main/java/org/elasticsearch/plugin/example/ExamplePluginConfiguration.java#L44), the plugin read config file from `path.conf`, (at least from [v2.0.0](https://github.com/elastic/elasticsearch/blob/v2.0.0-beta1/plugins/jvm-example/src/main/java/org/elasticsearch/plugin/example/ExamplePluginConfiguration.java#L44) )

When I upgrade plugin `analysis-ik`, I don't want re-configure the dict, the xml.

We should put config out of plugin dir, **and my patch also support load from plugin dir.**

### CODE REVIEW

**Comment by RobberPhex** [comment]
@medcl #192 is too complex to support load from plugin dir, so I rewrite the patch.

**Comment by medcl** [comment]
@RobberPhex  can you change the installed config folder: `config/analysis-ik/ik/` to `config/analysis-ik/`?
Thanks

**Comment by RobberPhex** [comment]
OK, I re-organize the config:

First try:
````
/etc/elasticsearch/analysis-ik$ tree
.
├── custom
│   ├── ext_stopword.dic
│   ├── mydict.dic
│   ├── single_word.dic
│   ├── single_word_full.dic
│   ├── single_word_low_freq.dic
│   └── sougou.dic
├── IKAnalyzer.cfg.xml
├── main.dic
├── preposition.dic
├── quantifier.dic
├── stopword.dic
├── suffix.dic
└── surname.dic
````
then, try:
````
/usr/share/elasticsearch/plugins/analysis-ik/config$ tree
.
├── custom
│   ├── ext_stopword.dic
│   ├── mydict.dic
│   ├── single_word.dic
│   ├── single_word_full.dic
│   ├── single_word_low_freq.dic
│   └── sougou.dic
├── IKAnalyzer.cfg.xml
├── main.dic
├── preposition.dic
├── quantifier.dic
├── stopword.dic
├── suffix.dic
└── surname.dic
````

**Comment by RobberPhex** [comment]
Add description for config's location.

**Comment by medcl** [comment]
Awesome,Thanks!

**Pull request merged**
