### PR TITLE
allow dir for ext dict&stopwords

### PR DESCRIPTION
**Pull request by figroc**
allow dir for `ext_dict` and `ext_stopwords` in IKAnalyzer.cfg.xml

### CODE REVIEW

**Comment by figroc** [comment]
we deploy es via docker. it's tedieus to mount files one by one into container. customizable dir structure will be far more flexible.

**Comment by medcl** [comment]
seems good to merge.

**Comment by figroc** [comment]
rebased and squashed

**Comment by medcl** [comment]
Thanks @figroc

**Pull request merged**
