### PR TITLE
move config file to <path.conf>/analysis-ik

### PR DESCRIPTION
**Pull request by RobberPhex**
[config files stay with plugin](https://github.com/medcl/elasticsearch-analysis-ik/commit/f9977456ee0135f9b9682e7a8e818da364b08cfa#diff-3e822f7015252733c7e5372514d9623cR38) is not friendly for upgrade elasticsearch or this plugin.

In [official example](https://github.com/elastic/elasticsearch/blob/2.3/plugins/jvm-example/src/main/java/org/elasticsearch/plugin/example/ExamplePluginConfiguration.java#L44), the plugin read config file from `path.conf`, (at least from [v2.0.0](https://github.com/elastic/elasticsearch/blob/v2.0.0-beta1/plugins/jvm-example/src/main/java/org/elasticsearch/plugin/example/ExamplePluginConfiguration.java#L44) )

When I upgrade plugin `analysis-ik`, I don't want re-configure the dict, the xml.

We should put config out of plugin dir, and put it in folder named with plugin name.

### CODE REVIEW

**Comment by medcl** [comment]
@RobberPhex 
Thanks for bring this pull request, please make sure the plugin will auto-detect the config path, which means the user can use the es's config path or just use the plugin's config path.

**Comment by RobberPhex** [comment]
@medcl When new config file is not exist, the plugin will load from plugin dir.

I add a deprecated warn for "load config file from plugin dir"

**Comment by medcl** [comment]
@RobberPhex 
java.io.FileNotFoundException: /xxx/xxx/config/analysis-ik/IKAnalyzer.cfg.xml (No such file or directory)

**Comment by RobberPhex** [comment]
@medcl 
Hi, the new config loading try to load xml from `/etc/elasticsearch/analysis-ik/IKAnalyzer.cfg.xml`, if not exist, try `/usr/share/elasticsearch/plugins/analysis-ik/config/ik/IKAnalyzer.cfg.xml`, if still failed, throw a Exception:
````
java.io.FileNotFoundException: /etc/elasticsearch/analysis-ik/IKAnalyzer.cfg.xml (No such file or directory)
````
So, user will add xml to `/etc/elasticsearch/analysis-ik/IKAnalyzer.cfg.xml`, which is standard config dir.

So, I think there is no inappropriate. Wait for you reply.

**Comment by medcl** [comment]
@RobberPhex please don't assume the plugin folder name is `analysis-ik`, there is no such guarantee

**Comment by RobberPhex** [comment]
Hi, @medcl 
When install the plugin, es will move `config` dir to `/etc/elasticsearch` and named with plugin name( from zip file), so put `IKAnalyzer.cfg.xml` to `/etc/elasticsearch/analysis-ik/IKAnalyzer.cfg.xml` is good.
If we use another name, it will confuse user by finding xml file.

For plugin name's hard code, Sorry for that, I just edit code, we can get plugin name from `AnalysisIkPlugin` (from everywhere).

**Comment by medcl** [comment]
@RobberPhex what if we don't use `plugin install` command, that will be cause failure, the basic install method(drop and unzip),we should also support it  :)

**Comment by RobberPhex** [comment]
@medcl 
this PR is too complex to support load from plugin dir, so I rewrite the patch. see #197

**Pull request closed without merging**
