### PR TITLE
将所有中文单字当作一个词

### PR DESCRIPTION
**Pull request by lvht**

### CODE REVIEW

**Comment by medcl** [comment]
建议增加开关，让用户外部可控制

**Comment by lufeng1102** [comment]
这个在新版本中会支持吗？因为用ik_max_word分词器，有些会产生单字，有些不能，有点奇怪。

`POST _analyze
{
  "analyzer": "ik_max_word",
  "text": "技能中华人民共和国"
}`
`{
  "tokens": [
    {
      "token": "技能",
      "start_offset": 0,
      "end_offset": 2,
      "type": "CN_WORD",
      "position": 0
    },
    {
      "token": "中华人民共和国",
      "start_offset": 2,
      "end_offset": 9,
      "type": "CN_WORD",
      "position": 1
    },
    {
      "token": "中华人民",
      "start_offset": 2,
      "end_offset": 6,
      "type": "CN_WORD",
      "position": 2
    },
    {
      "token": "中华",
      "start_offset": 2,
      "end_offset": 4,
      "type": "CN_WORD",
      "position": 3
    },
    {
      "token": "华人",
      "start_offset": 3,
      "end_offset": 5,
      "type": "CN_WORD",
      "position": 4
    },
    {
      "token": "人民共和国",
      "start_offset": 4,
      "end_offset": 9,
      "type": "CN_WORD",
      "position": 5
    },
    {
      "token": "人民",
      "start_offset": 4,
      "end_offset": 6,
      "type": "CN_WORD",
      "position": 6
    },
    {
      "token": "共和国",
      "start_offset": 6,
      "end_offset": 9,
      "type": "CN_WORD",
      "position": 7
    },
    {
      "token": "共和",
      "start_offset": 6,
      "end_offset": 8,
      "type": "CN_WORD",
      "position": 8
    },
    {
      "token": "国",
      "start_offset": 8,
      "end_offset": 9,
      "type": "CN_CHAR",
      "position": 9
    }
  ]
}`

**Comment by zhiho** [comment]
单字的token要怎么处理？单字在全文搜索的时候容易命中

**Comment by lufeng1102** [comment]
是的，切到单字会提高召回率，但准确率会下降。

**Pull request closed without merging**
